apiVersion: v1
kind: Service
metadata:
  name: monitoring-demo-app-service
  namespace: monitoring-demo-app
spec:
  selector:
    app: monitoring-demo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer